### PR TITLE
Add modal to project cards

### PR DESCRIPTION
**Pull request by BhavyaSheth22**
Added modal for large project descriptions on project card.

Screenshot from 2021-02-16 19-33-40

### CODE REVIEW

**Comment by ShubhankarKG** [comment]
Can we have the image also? That would look good I feel.

cc/ @Saif807380

**Comment by Saif807380** [comment]
Good work! Just a few changes - 

- Can you reduce the width of the modal?
- Remove the horizontal scrollbar
- As @ShubhankarKG mentioned add the image as well so the modal would look like image, name and desc vertically top to bottom

**Comment by BhavyaSheth22** [comment]
I have made the following changes:

> Good work! Just a few changes -
> 
> * Can you reduce the width of the modal?

I've done that for bigger screens, although on smaller screens the width remains more.
> * Remove the horizontal scrollbar

Done!
> * As @ShubhankarKG mentioned add the image as well so the modal would look like image, name and desc vertically top to bottom

This order looked weird, I changed it to title, image and description.

I also changed the text to trigger modal from anchor to button.

**Comment by Saif807380** [comment]
Looks great!

**Review by ShubhankarKG — APPROVED** [review]
LGTM, Thanks!

**Pull request merged**
