### PR TITLE
404 not found page

### PR DESCRIPTION
**Pull request by ShubhankarKG**
Tasks
- [x] Displays error page on global route error
- [ ] Displays error page on nested route error

Screenshot from 2020-12-21 15-20-51

### CODE REVIEW

**Comment by Saif807380** [comment]
LGTM. We'll just have to customize it so that it becomes consistent with the final theme of the website as and when that's decided

**Comment by akshatshah21** [comment]
Suggestion: We can add some text that says something like
> If you think there should be a page here, please create an issue at [the website repository](https://github.com/CommunityOfCoders/COCWebsite)

Also, can we merge this into master? If and when we implement a theme, it'll mostly be using MUI's `ThemeProvider` at the top level (like in #105), so it'll apply to the `NotFound` component also.

**Comment by ShubhankarKG** [comment]
> If you think there should be a page here, please create an issue at [the website repository](https://github.com/CommunityOfCoders/COCWebsite)

I added this in the 404 component.

Handling dynamic links seem to be a problem right now, since our API does not follow a fixed shape. To better handle dynamic link 404s (like typing an event ID wrong), we would need to do some stuff:
- Standardize our API
- Centralize all our requests in client side.

This will take some time, and we don't have the necessary time right now. So, we can maybe tackle the dynamic 404s in a later stage.

**Comment by ShubhankarKG** [comment]
I am merging this one then.

**Pull request merged**
