### PR TITLE
FIx footer covering content

### LINKED ISSUE #68: Footer covers content
As pointed out by @ShubhankarKG , the footer from #65 covers the main content.
image

### PR DESCRIPTION
**Pull request by akshatshah21**
Fixes #68 

The entire ".App" div is now a flex container

Appears to be working properly on all pages, except:
1. On Blogs page, it appears that the footer is covering the FAB. But the FAB is still on top of the footer, it's its color that makes it
appear so.

The fix is a significant change. The App div is changed to MUI Box, and the Header, Footer and  Switch are Box items inside it.
And the only way I found to make the footer stay at the bottom was to add a minHeight to the main content (Switch):
https://github.com/CommunityOfCoders/COCWebsite/compare/CommunityOfCoders:8ccf5bf...akshatshah21:5512ee7#diff-65a9f8e865a8a715f177f365cbb9c9e66d5cb105440ea5e92f895c96d2d9d5b2R47-R48

So on empty pages or pages with really little content, it appears like this at 100% zoom:
image

While it appears just as it should with other content:
image

### CODE REVIEW

**Comment by akshatshah21** [comment]
I have removed `style={{maxHeight: "87vh"}}`  from the Signin and Signup `Grid`s, since that was the reason of the overlap with the footer, mentioned in #68   
As far as what I could test, this hasn't caused any side-effects.

**Comment by akshatshah21** [comment]
@ShubhankarKG please review this

**Review by ShubhankarKG — APPROVED** [review]
Thanks! As is, all the pages look good. Didn't see any glitch on footer. Hopefully this should be resolved now. Let's wait for @Saif807380 to have a look.

**Comment by Saif807380** [comment]
Everything looks great, we can go ahead and merge this.

**Pull request merged**
