### PR TITLE
Events Updated UI

### PR DESCRIPTION
**Pull request by shekokar**
Updated the UI for events page

1. Added banner
2. Grouped events based on upcoming events & past events

The 'Create Event', 'Edit Event' and 'Delete Event' buttons are rendered depending upon whether the user is a member or not.

Screenshot from 2021-01-15 18-54-41
Screenshot from 2021-01-15 18-54-49
Screenshot from 2021-01-15 18-54-53

### CODE REVIEW

**Review by ShubhankarKG — CHANGES_REQUESTED** [review]
Thanks for starting this, the code looks good, I just had a few suggestions.
1. Can we use `.webp` image for the Banner? That'll help in the performance
2. The `Banner.scss` looks a whole lot similar to the one in Homepage. If the functionality stays the same, can you please extract this into a mixin in Utilities? More details can be found [here](https://sass-lang.com/documentation/at-rules/mixin).
3. Events need to be supplied an image, which, in most cases will be the poster. For now, can you please filter the events out so that only events with valid images are shown?
4. While we are at it, please add the uploads/ directory to `.gitignore` 

Thanks.

**Comment by himanshuMaheshwari2311** [comment]
This looks good, the design is good. Few things I'd like to add:
1. Add a default image for events if user are not uploading, this will ensure your cards are of same height giving a better feel
2. Improve the look and feel of content of the card, for eg. add horizontal rule after header, work on spacing between time and menu, again a horizontal rule for the footer
3. I am assuming font will be changed as recommended by Breejesh for the entire website

**Comment by shekokar** [comment]
Along with the changes suggested by @himanshuMaheshwari2311, I have also updated the image aspect ratio to 1:1, considering that CoC posters are of that ratio.

Screenshot from 2021-01-23 20-57-24

**Review by ShubhankarKG — APPROVED** [review]
LGTM, Thanks! Let's wait for @Saif807380 to have a look.

**Pull request merged**
