### PR TITLE
Fixed Typewriter Effect

### LINKED ISSUE #89: Typewriter Effect in Home component causes content below it to move vertically
On smaller screens (about 370px and lower width), the words in the typewriter effect cause the content below to move up and down:
typewriter-effect issue

This makes scrolling down and reading a little inconvenient.

### PR DESCRIPTION
**Pull request by AMMAR-62**
Solved the issue "Typewriter Effect in Home component causes content below it to move vertically" ... commit me specify nahi kiya acche ... so

Fixes #89

### CODE REVIEW

**Comment by ShubhankarKG** [comment]
Requesting @akshatshah21 to have a look .

**Comment by akshatshah21** [comment]
Thanks for this @AMMAR-62! I will review this in some time.

**Comment by akshatshah21** [comment]
Okay, so turns out I'd tried this before, and the following images show what the problem is. The line containing "by" stays empty, and it looks weird. 
image
image

Can you find a way that leaves some space for the text to appear after and then below the line "For the juniors, by" if required? Maybe something to do with specifying the height of the element in which this text appears.

**Comment by AMMAR-62** [comment]
Cool... i'll try

**Comment by AMMAR-62** [comment]
Some minor issue still prevails for iphone X ... may need to adjust the width... but probably not so noticeable

**Comment by akshatshah21** [comment]
> Some minor issue still prevails for iphone X ... may need to adjust the width... but probably not so noticeable

Can you be more specific? I didn't notice any issue. Add a screenshot if required.
The changes look good, great work!

**Comment by AMMAR-62** [comment]
https://user-images.githubusercontent.com/53120491/108054251-6b153000-7074-11eb-9e45-58c70f2833f0.mp4

**Comment by AMMAR-62** [comment]
>  avc_record_000004.mp4

it is a minor issue ... probably non-noticeable

**Comment by ShubhankarKG** [comment]
Going ahead with merging this then.

**Pull request merged**
