### PR TITLE
Modal component for add event section

### PR DESCRIPTION
**Pull request by AtharvaThorve**
This is for issue #56.

Screenshot (40)

Screenshot (41)

I did not try filling the form and adding a new event.

### CODE REVIEW

**Review by ShubhankarKG — CHANGES_REQUESTED** [review]
Thanks for filing this! There are a few functionality flaws currently. Kindly fix them as well :pray: 

1. If I submit an event, the modal doesn't get closed and so, the page doesn't get refreshed.
2. The warning modal should have loseFocus disabled, meaning that the modal should not close if I click anywhere else.
3. The warning modal has an `x`, that symbolises cancel. Clicking that should not close all the modals, but should keep the modal with the form on.

Also, A little design suggestion:
1. There's too much margin on the x-axis for the add event. If possible, we can have a conditional style that reduces this margin if the page is an AddEvent and keeps the margin if the page is EditEvent.

Thanks.

**Comment by AtharvaThorve** [comment]
The stated issues have been fixed
For the x-axis margin issue currently, the size of the modal has been increased and the margin of `AddEvent` component has been decreased.

**Review by ShubhankarKG — APPROVED** [review]
Thanks, LGTM!

**Comment by ShubhankarKG** [comment]
I'll create the missing parts in a followup issue, so we can merge this one.

**Pull request merged**
