### PR TITLE
Navbar Enhancements

### LINKED ISSUE #103: Navbar UI enhancement
A few changes are required in the navbar - 
- Right-align all the auth links and left-align everything else
- Navbar overlaps content from various pages
- Navbar should not stick to the top while scrolling
- In mobile view, the hamburger icon isn't visible as both the icon and the backgrounds of a few pages are white in colour

### PR DESCRIPTION
**Pull request by akshatshah21**
Closes #103 

- [x] Right-align all the auth links and left-align everything else
- [x] Navbar does not overlap content from various pages
- [x] Navbar does not stick to the top while scrolling
- [x] In mobile view, the hamburger icon is now visible, with a translucent black background.
navbar-enhancements

### CODE REVIEW

**Comment by Saif807380** [comment]
Great Work! I had one question though
Screenshot 2021-02-10 at 21 07 34

Logout has an underline as well. Is that the intended behaviour? This line is present only when the user is on the home page and not for the other pages.

**Comment by akshatshah21** [comment]
I'll look into this. Also, in the screenshot the Logout and Signup links are being shown at the same time

**Comment by Saif807380** [comment]
> I'll look into this. Also, in the screenshot the Logout and Signup links are being shown at the same time

Yes that will need fixing as well

**Comment by akshatshah21** [comment]
Updates:
1. Fixed the underline issue
2. Correct auth nav links

**Review by Saif807380 — APPROVED** [review]
Good work. I'll go ahead and merge this.

**Pull request merged**
