### PR TITLE
About Us: Responsive

### PR DESCRIPTION
**Pull request by akshatshah21**
image
image
image

```css
.secretaries-image {
  width: 50vw;
}

.team-image {
  width: 80vw;
}

@media only screen and (max-width: 768px) {
  .secretaries-image {
    width: 80vw;
  }
}
```

### CODE REVIEW

**Comment by akshatshah21** [comment]
I've made font sizes responsive, so it looks better on smaller screens now.
Before:
responsive about
After:
responsive about 2

**Comment by akshatshah21** [comment]
Updates:
1. Added the `responsiveFontSizes` MUI theme to the entire `Box` of the main content (see `App.js`)
2. Reduced the content of the About Page, and some UI changes

about-phone

image
image
 
I also noticed that the order of image-text alternating columns changes on smaller screens. I haven't found a way to fix this.

**Comment by ShubhankarKG** [comment]
There seems to be a padding issue here:

Screenshot from 2021-02-13 18-27-13

**Comment by akshatshah21** [comment]
> There seems to be a padding issue here:
> 
> Screenshot from 2021-02-13 18-27-13
> 

Top padding for the image?

**Comment by ShubhankarKG** [comment]
Yes, either some padding or a line break most probably should work

**Comment by akshatshah21** [comment]
1. Fix ordering of Engaging Discussions and Project Building
2. Added the requested padding before Interactive Workshops
3. Center align text vertically with the images (the three grids in What We Do)

about
about2

**Review by ShubhankarKG — APPROVED** [review]
LGTM, Thanks

**Pull request merged**
