### PR TITLE
About us

### PR DESCRIPTION
**Pull request by ShubhankarKG**
First draft for About Us page.
Screenshot from 2020-12-20 17-44-44
Screenshot from 2020-12-20 17-44-57
Screenshot from 2020-12-20 17-45-03
Screenshot from 2020-12-20 17-45-10

### CODE REVIEW

**Comment by Saif807380** [comment]
A few changes - 

- Some vertical margin to the grey container would look good
- Some vertical padding as well
- Can we reduce the space between the `h1` and the `p` tags?
- Change the `About CoC` to just `About` or `About Us` as it will be obvious who we are talking about
- Change the order of the questions to Who, What, How, When
- `Sounds good? ` would look better as an `h3` or an `h4`

**Comment by ShubhankarKG** [comment]
made the requested changes

**Comment by akshatshah21** [comment]
I suggest using `responsiveFontSizes` from MUI for better font sizing on smaller sreens.
```javascript
import { createMuiTheme, responsiveFontSizes } from '@material-ui/core/styles';

let theme = createMuiTheme();
theme = responsiveFontSizes(theme);
```

And then use a `ThemeProvider` to wrap everything in the theme

**Comment by ShubhankarKG** [comment]
Would you mind updating these in your PR itself?

**Comment by akshatshah21** [comment]
A suggestion: Reduce the contents of the first few paragraphs, or move it down. It appears too long and loses interest immediately because of it.

**Comment by ShubhankarKG** [comment]
Courtesy #105 , merging this one

**Pull request merged**
