### PR TITLE
added the new homepage

### PR DESCRIPTION
**Pull request by Leovaldez42**

### CODE REVIEW

**Comment by Saif807380** [comment]
The page looks amazing! Just a few a minute changes -
- Can we use the below image in place of writing `Community of Coders`? The original image has the text in white, hence I've attached a screenshot of it. [Original Image](https://drive.google.com/file/d/13QnTCv6W1pyj_fn3aLn4taqz49Ef47KM/view?usp=sharing)
Screenshot 2020-12-28 at 18 37 29

- If the image cannot be used, then can we at least get the name in one line?
- Can we separate `IMAGINE     BELIEVE     ACHIEVE` these using `|` in between them?
- Remove left margin on the `Learn More` anchor tag.
- Reduce the size of the `Learn More` button.
- Remove the `:` after `Our Mission`.
- Change the font-weight of the mission line from bold to normal.

**Comment by Leovaldez42** [comment]
- Image can be used but what of in mobile view, when the image becomes bigger than the screen size
- It is in one line only
- Yes. done
- Which anchor tag?
- It will become unsymmetrical
- Done
- Done

**Comment by Saif807380** [comment]
All changes look great. I was talking about the margin on this a tag. If we remove the margin then it becomes properly aligned with the text above it.
Screenshot 2020-12-29 at 12 23 17

**Comment by ShubhankarKG** [comment]
Fixed the margin!

**Pull request merged**
