### PR TITLE
Spinner Component added

### PR DESCRIPTION
**Pull request by AtharvaThorve**
This PR is for issue #42 
A spinner is visible when the events page, the glimpses page, and the blogs page is visible. Sometimes calls happen so fast that sometimes it is only visible for a split second.
Tagging @ShubhankarKG so you get notified of this PR.

### CODE REVIEW

**Comment by ShubhankarKG** [comment]
Missed out the IndividualImageGallery i guess, please add the spinner there as well.

**Review by ShubhankarKG — COMMENTED** [review]
Thanks, looks good! But a lot of diff is due to formatting, do you think you can maybe undo the formatting? It's not compulsory though, but it'll reduce the diff size :sweat_smile: 

Let's wait for @Saif807380 to review the UI part a bit.

**Comment by Saif807380** [comment]
I think the spinner should be at the centre of the page rather than at the top. Also, we'll have to change its colour once we finalize the colour scheme.

**Comment by Saif807380** [comment]
Can you undo the formatting if it's not much of an inconvenience? The large diff could cause a problem while merging.

**Comment by AtharvaThorve** [comment]
The diff has been decreased.
The work on the spinner component being displayed at the center is still going on.

**Pull request merged**
