### PR TITLE
UI and Routing improvements added to blogs

### PR DESCRIPTION
**Pull request by AtharvaThorve**
UI and Routing improved and added a new Alert utility component which can be used at many different locations.

### CODE REVIEW

**Comment by ShubhankarKG** [comment]
@AtharvaThorve can you please start working on this one? With a fresh auth module now, I'm sure this should be a bit easier now.

**Comment by AtharvaThorve** [comment]
Rebased with the master branch that is why so many commits are present.

**Comment by ShubhankarKG** [comment]
Can you please squash the commits :sweat_smile: ? It will help in a faster review

**Review by ShubhankarKG — APPROVED** [review]
Thanks for the updates @AtharvaThorve , I pushed some commits to ensure that 
1. Only I can edit and delete my blogs
2. I cannot change my username while adding a blog.

**Pull request merged**
